import type { Swimmer } from "./types";

export const swimmers: Swimmer[] = [
  {
    id: "leon-marchand",
    name: "Léon Marchand",
    country: "FRA",
    gender: "M",
    archetype: "UNIVERSAL",
    events: ["200IM", "400IM", "200FLY", "200BREAST"],
    attributes: { start: 88, speed: 89, power: 95, technique: 96, endurance: 94, consistency: 93 },
    ovr: 95,
    basePrice: 215,
    photo: "/leon-card.png",
    color: "#3a8dff",
  },
  {
    id: "summer-mcintosh",
    name: "Summer McIntosh",
    country: "CAN",
    gender: "F",
    archetype: "UNIVERSAL",
    events: ["200FLY", "400IM", "400FREE", "200IM"],
    attributes: { start: 86, speed: 88, power: 92, technique: 95, endurance: 96, consistency: 94 },
    ovr: 94,
    basePrice: 210,
    photo: "/summer-card.png",
    color: "#f5c542",
  },
  {
    id: "katie-ledecky",
    name: "Katie Ledecky",
    country: "USA",
    gender: "F",
    archetype: "DISTANCE",
    events: ["400FREE", "800FREE", "1500FREE"],
    attributes: { start: 78, speed: 84, power: 88, technique: 96, endurance: 99, consistency: 97 },
    ovr: 94,
    basePrice: 200,
    photo: "/ledecky-card.png",
    color: "#4da3ff",
  },
  {
    id: "kaylee-mckeown",
    name: "Kaylee McKeown",
    country: "AUS",
    gender: "F",
    archetype: "UNIVERSAL",
    events: ["100BACK", "200BACK", "200IM"],
    attributes: { start: 91, speed: 92, power: 89, technique: 94, endurance: 90, consistency: 95 },
    ovr: 93,
    basePrice: 190,
    photo: "/mckeown-card.png",
    color: "#3fbf6f",
  },
  {
    id: "pan-zhanle",
    name: "Pan Zhanle",
    country: "CHN",
    gender: "M",
    archetype: "SPRINT",
    events: ["50FREE", "100FREE"],
    attributes: { start: 95, speed: 99, power: 90, technique: 88, endurance: 75, consistency: 88 },
    ovr: 92,
    basePrice: 185,
    color: "#ff5b5b",
  },
  {
    id: "david-popovici",
    name: "David Popovici",
    country: "ROU",
    gender: "M",
    archetype: "SPRINT",
    events: ["100FREE", "200FREE"],
    attributes: { start: 92, speed: 96, power: 86, technique: 95, endurance: 82, consistency: 90 },
    ovr: 91,
    basePrice: 180,
    color: "#fff15b",
  },
  {
    id: "mollie-ocallaghan",
    name: "Mollie O'Callaghan",
    country: "AUS",
    gender: "F",
    archetype: "SPRINT",
    events: ["100FREE", "200FREE"],
    attributes: { start: 90, speed: 95, power: 87, technique: 93, endurance: 84, consistency: 92 },
    ovr: 91,
    basePrice: 178,
    color: "#3fbf6f",
  },
  {
    id: "kristof-milak",
    name: "Kristóf Milák",
    country: "HUN",
    gender: "M",
    archetype: "UNIVERSAL",
    events: ["100FLY", "200FLY", "200FREE"],
    attributes: { start: 87, speed: 92, power: 94, technique: 93, endurance: 86, consistency: 87 },
    ovr: 91,
    basePrice: 170,
    color: "#7fff5b",
  },
  {
    id: "ariarne-titmus",
    name: "Ariarne Titmus",
    country: "AUS",
    gender: "F",
    archetype: "DISTANCE",
    events: ["400FREE", "800FREE", "200FREE"],
    attributes: { start: 82, speed: 88, power: 86, technique: 93, endurance: 96, consistency: 94 },
    ovr: 91,
    basePrice: 175,
    color: "#3fbf6f",
  },
  {
    id: "kate-douglass",
    name: "Kate Douglass",
    country: "USA",
    gender: "F",
    archetype: "UNIVERSAL",
    events: ["200IM", "200BREAST", "100FREE"],
    attributes: { start: 89, speed: 90, power: 92, technique: 94, endurance: 86, consistency: 93 },
    ovr: 90,
    basePrice: 168,
    photo: "/douglass-card.png",
    color: "#b06cff",
  },
  {
    id: "regan-smith",
    name: "Regan Smith",
    country: "USA",
    gender: "F",
    archetype: "UNIVERSAL",
    events: ["100BACK", "200BACK", "200FLY"],
    attributes: { start: 88, speed: 90, power: 87, technique: 94, endurance: 88, consistency: 92 },
    ovr: 90,
    basePrice: 165,
    color: "#4da3ff",
  },
  {
    id: "sarah-sjostrom",
    name: "Sarah Sjöström",
    country: "SWE",
    gender: "F",
    archetype: "SPRINT",
    events: ["50FREE", "100FREE", "50FLY", "100FLY"],
    attributes: { start: 93, speed: 96, power: 91, technique: 95, endurance: 78, consistency: 91 },
    ovr: 90,
    basePrice: 162,
    color: "#ffe680",
  },
  {
    id: "bobby-finke",
    name: "Bobby Finke",
    country: "USA",
    gender: "M",
    archetype: "DISTANCE",
    events: ["800FREE", "1500FREE"],
    attributes: { start: 75, speed: 82, power: 84, technique: 90, endurance: 98, consistency: 93 },
    ovr: 89,
    basePrice: 155,
    color: "#4da3ff",
  },
  {
    id: "daniel-wiffen",
    name: "Daniel Wiffen",
    country: "IRL",
    gender: "M",
    archetype: "DISTANCE",
    events: ["800FREE", "1500FREE", "400FREE"],
    attributes: { start: 78, speed: 84, power: 85, technique: 91, endurance: 97, consistency: 90 },
    ovr: 89,
    basePrice: 152,
    color: "#3fbf6f",
  },
  {
    id: "lukas-martens",
    name: "Lukas Märtens",
    country: "GER",
    gender: "M",
    archetype: "DISTANCE",
    events: ["400FREE", "800FREE", "200FREE"],
    attributes: { start: 82, speed: 89, power: 87, technique: 92, endurance: 95, consistency: 89 },
    ovr: 89,
    basePrice: 150,
    color: "#fff15b",
  },
  {
    id: "thomas-ceccon",
    name: "Thomas Ceccon",
    country: "ITA",
    gender: "M",
    archetype: "UNIVERSAL",
    events: ["100BACK", "50BACK", "100FLY"],
    attributes: { start: 92, speed: 93, power: 88, technique: 91, endurance: 80, consistency: 88 },
    ovr: 89,
    basePrice: 148,
    color: "#3fbf6f",
  },
  {
    id: "torri-huske",
    name: "Torri Huske",
    country: "USA",
    gender: "F",
    archetype: "SPRINT",
    events: ["100FLY", "100FREE", "50FREE"],
    attributes: { start: 92, speed: 94, power: 87, technique: 92, endurance: 78, consistency: 90 },
    ovr: 89,
    basePrice: 148,
    color: "#ff7b54",
  },
  {
    id: "siobhan-haughey",
    name: "Siobhán Haughey",
    country: "HKG",
    gender: "F",
    archetype: "UNIVERSAL",
    events: ["100FREE", "200FREE", "100BREAST"],
    attributes: { start: 87, speed: 92, power: 86, technique: 91, endurance: 87, consistency: 91 },
    ovr: 88,
    basePrice: 145,
    color: "#ff5b5b",
  },
  {
    id: "adam-peaty",
    name: "Adam Peaty",
    country: "GBR",
    gender: "M",
    archetype: "SPRINT",
    events: ["50BREAST", "100BREAST"],
    attributes: { start: 91, speed: 95, power: 96, technique: 92, endurance: 70, consistency: 86 },
    ovr: 88,
    basePrice: 142,
    color: "#4da3ff",
  },
  {
    id: "tatjana-smith",
    name: "Tatjana Smith",
    country: "RSA",
    gender: "F",
    archetype: "SPRINT",
    events: ["50BREAST", "100BREAST", "200BREAST"],
    attributes: { start: 88, speed: 91, power: 90, technique: 92, endurance: 82, consistency: 90 },
    ovr: 88,
    basePrice: 140,
    color: "#7fff5b",
  },
  {
    id: "yufei-zhang",
    name: "Zhang Yufei",
    country: "CHN",
    gender: "F",
    archetype: "UNIVERSAL",
    events: ["100FLY", "200FLY", "50FLY"],
    attributes: { start: 88, speed: 92, power: 89, technique: 92, endurance: 84, consistency: 89 },
    ovr: 87,
    basePrice: 138,
    color: "#ff5b5b",
  },
  {
    id: "nicolo-martinenghi",
    name: "Nicolò Martinenghi",
    country: "ITA",
    gender: "M",
    archetype: "SPRINT",
    events: ["50BREAST", "100BREAST"],
    attributes: { start: 90, speed: 93, power: 91, technique: 88, endurance: 74, consistency: 87 },
    ovr: 87,
    basePrice: 132,
    color: "#3fbf6f",
  },
  {
    id: "gregorio-paltrinieri",
    name: "Gregorio Paltrinieri",
    country: "ITA",
    gender: "M",
    archetype: "DISTANCE",
    events: ["1500FREE", "800FREE"],
    attributes: { start: 76, speed: 82, power: 83, technique: 89, endurance: 96, consistency: 88 },
    ovr: 87,
    basePrice: 128,
    color: "#4da3ff",
  },
  {
    id: "maxime-grousset",
    name: "Maxime Grousset",
    country: "FRA",
    gender: "M",
    archetype: "SPRINT",
    events: ["50FREE", "100FREE", "100FLY"],
    attributes: { start: 91, speed: 93, power: 86, technique: 88, endurance: 76, consistency: 86 },
    ovr: 87,
    basePrice: 128,
    color: "#3a8dff",
  },
  {
    id: "hubert-kos",
    name: "Hubert Kós",
    country: "HUN",
    gender: "M",
    archetype: "OTHER",
    events: ["200BACK", "100BACK"],
    attributes: { start: 87, speed: 89, power: 87, technique: 93, endurance: 88, consistency: 87 },
    ovr: 86,
    basePrice: 122,
    color: "#7fff5b",
  },
  {
    id: "sam-short",
    name: "Sam Short",
    country: "AUS",
    gender: "M",
    archetype: "DISTANCE",
    events: ["400FREE", "800FREE", "1500FREE"],
    attributes: { start: 80, speed: 85, power: 84, technique: 90, endurance: 95, consistency: 86 },
    ovr: 86,
    basePrice: 118,
    color: "#3fbf6f",
  },
  {
    id: "marrit-steenbergen",
    name: "Marrit Steenbergen",
    country: "NED",
    gender: "F",
    archetype: "UNIVERSAL",
    events: ["100FREE", "200FREE", "200IM"],
    attributes: { start: 85, speed: 88, power: 85, technique: 90, endurance: 86, consistency: 88 },
    ovr: 85,
    basePrice: 115,
    photo: "/steenbergen-card.png",
    color: "#ff7b54",
  },
  {
    id: "erika-fairweather",
    name: "Erika Fairweather",
    country: "NZL",
    gender: "F",
    archetype: "DISTANCE",
    events: ["400FREE", "800FREE", "200FREE"],
    attributes: { start: 81, speed: 86, power: 84, technique: 90, endurance: 93, consistency: 87 },
    ovr: 85,
    basePrice: 110,
    color: "#000000",
  },
  {
    id: "anastasia-gorbenko",
    name: "Anastasia Gorbenko",
    country: "ISR",
    gender: "F",
    archetype: "UNIVERSAL",
    events: ["200IM", "400IM", "200BACK"],
    attributes: { start: 84, speed: 86, power: 85, technique: 90, endurance: 89, consistency: 86 },
    ovr: 84,
    basePrice: 102,
    color: "#3a8dff",
  },
  {
    id: "angharad-evans",
    name: "Angharad Evans",
    country: "GBR",
    gender: "F",
    archetype: "SPRINT",
    events: ["100BREAST", "50BREAST"],
    attributes: { start: 86, speed: 89, power: 87, technique: 88, endurance: 76, consistency: 84 },
    ovr: 83,
    basePrice: 95,
    photo: "/evans-card.png",
    color: "#ff7b54",
  },
];

export function getSwimmer(id: string): Swimmer | undefined {
  return swimmers.find((s) => s.id === id);
}

export function getSwimmerPrice(swimmer: Swimmer): number {
  return swimmer.basePrice;
}
